### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icons did not comply within the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#color). The "tool" icon at the corner was really out of line with eOS HIG guidlines (see the pun?) regarding the implementation of pictogram. It wasn't extruded nor inset. Furthermore, it also doesn't comply by the eOS HIG rules regarding highlight and shadows for the tool in the corner.
I've look into 
As for the other app icons, it's too on the nose regarding to what the each icons represent. I've look into your apps and there is already an explanation to what the button does. In that case, the icon doesn't have to be super clear and detailed to what it represents. Instead, they should be moe abstract and be more focused on being aesthetically pleasing. For obvious reason I have mentioned.

### CODE REVIEW

**Comment by Fatih20** [comment]
Which parts are too transparent?
Do you think I should add a white rectangle as base shape below everything?

**Comment by NathanBnm** [comment]
I mean, on most of the icons there is the "PDF" symbol in background, on which you added a magic wand, or an arrow.

And for the merge, and cut icons you removed this background. I'm worried about how it will be rendered in the UI.

I think you should keep the design you made but with the background added back.

Do you understand what I mean?

**Comment by Fatih20** [comment]
Oh yeah, there were some technical issues on my side. Will be fixing that soon. Thanks for pointing that out.

**Comment by muriloventuroso** [comment]
I agree with @NathanBnm . With the transparent icons the aim of the icon is lost, it is difficult to identify the action.

**Comment by Fatih20** [comment]
No, it's not an aim. It's a technical issue, there's supposed to be a PDF icon there.

**Comment by Fatih20** [comment]
There, fixed it.

**Comment by Fatih20** [comment]
Can you please credit me for the icon? Thank you!

**Comment by muriloventuroso** [comment]
Of course, I will provide new screenshots and update the credits.

**Comment by Fatih20** [comment]
Credit me in the release notes, please. :)

**Pull request merged**
